version: '3'
services:
  nginx:
    restart: always
    image: nivankovic/multi-nginx
    ports:
      - '80:80'
    depends_on:
      - api
      - client

  api:
    image: nivankovic/multi-server 
   
  client:
    image: nivankovic/multi-client
  
  worker:
    image: nivankovic/multi-worker
