version: '3'
services:
  nginx:
    restart: always
    image: nivankovic/multi-nginx
    ports:
      - '80:80'
    depends_on:
      - api
      - client

  api:
    image: nivankovic/multi-server 
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}

  client:
    image: nivankovic/multi-client
  
  worker:
    image: nivankovic/multi-worker
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
