name: Multi - Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-push-to-dockerhub:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Client Docker image
      with:
        image: nivankovic/multi-client
        tags: ${{ github.run_attempt }}, latest
        registry: docker.io
        dockerfile: ./client/Dockerfile
        directory: ./client
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Nginx Docker image
      with:
        image: nivankovic/multi-nginx
        tags: ${{ github.run_attempt }}, latest
        registry: docker.io
        dockerfile: ./nginx/Dockerfile
        directory: ./nginx
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Server Docker image
      with:
        image: nivankovic/multi-server
        tags: ${{ github.run_attempt }}, latest
        registry: docker.io
        dockerfile: server/Dockerfile
        directory: server
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Worker Docker image
      with:
        image: nivankovic/multi-worker
        tags: ${{ github.run_attempt }}, latest
        registry: docker.io
        dockerfile: worker/Dockerfile
        directory: worker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
