name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Client Docker image for testing
      run: docker build --file ./client/Dockerfile.dev --tag nivankovic/react-test ./client
    - name: Run the Client app tests
      run: docker run -e CI=true nivankovic/react-test npm test -- --coverage
